name: Block bad filenames

on: [push, pull_request]

jobs:
  check-filenames:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for invalid filenames (Windows incompatible)
        run: |
          echo "🔍 Checking for bad filenames..."
          forbidden='CON PRN AUX NUL COM1 COM2 COM3 COM4 COM5 COM6 COM7 COM8 COM9 LPT1 LPT2 LPT3 LPT4 LPT5 LPT6 LPT7 LPT8 LPT9'
          has_error=0

          for file in $(git ls-files); do
            for word in $forbidden; do
              if echo "$file" | grep -iqE "(^|/)$word(\..*)?$"; then
                echo "❌ Invalid Windows filename detected: $file"
                has_error=1
              fi
            done
          done

          if [ $has_error -eq 1 ]; then
            echo "⛔ Push blocked due to Windows-incompatible filenames."
            exit 1
          fi

          echo "✅ All filenames OK."
